#!/bin/bash 

echo -e " 更新源中....."
apt-get update
apt-get install -y dirmngr

echo -e " 给kali更新源加key "
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ED444FF07D8D0BF6

echo -e "更换kali更新源 默认更新源是阿里镜像 "
cat <<EOF > /etc/apt/sources.list
#aliyun
deb http://mirrors.aliyun.com/kali kali-rolling main non-free contrib
deb-src http://mirrors.aliyun.com/kali kali-rolling main non-free contrib
EOF

echo -e " 更新系统并安装kali "
apt-get update
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get -y autoremove --purge
apt-get -y install kali-linux*

echo -e "清理垃圾中...."
apt-get -y autoremove --purge
apt-get clean
#vnc部分可以选择注释
echo -e "VNC选项"
echo -e "\n是否安装图形化界面和VNC?"
echo -e "\n 1. 我安装图像化界面和VNC"
echo -e "\n 2. 我不需要这些，可以退出安装程序了"
while :
do
  read InputeChoice
  case $InputeChoice in
	1)
		  apt-get install xfce4 xfce4-goodies xorg lxde-core tightvncserver -y --allow-unauthenticated
		vncserver
		vncserver -kill :1
		sed -i '171i $localhost="no"; ' /etc/vnc.conf   #开放监听地址，不再仅限本地使用
		chmod +x /etc/vnc.conf
		mv ~/.vnc/xstartup ~/.vnc/xstartup.bak
		echo "#!/bin/bash
		xrdb $HOME/.Xresources
		startxfce4 &
		lxterminal &
		/usr/bin/lxsession -s LXDE &" >> ~/.vnc/xstartup
		  chmod +x ~/.vnc/xstartup
		echo "#!/bin/bash
		PATH="$PATH:/usr/bin/"
		export USER="user"
		DISPLAY="1"
		DEPTH="16"
		GEOMETRY="1024x768"
		OPTIONS="-depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY} -localhost"
		. /lib/lsb/init-functions" >> /etc/init.d/vncserver
		  chmod +x /etc/init.d/vncserver
		rm /etc/hostname
		echo "Kali" >> /etc/hostname
		vncserver
		clear
		echo -e "============================================================================================================================="
		myip="$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com)"  #显示自己公网ip
		echo "Connect it!!! Using :-  ${myip}:1 in VNC Viewer"
		echo -e "============================================================================================================================="
		break
		;;
	2)
  echo -e "============================================================================================================================="
  echo -e "您最好自己重启下系统，感谢您的使用，bye"
  echo -e "============================================================================================================================="
		break
		;;
 esac
echo -e " 接下来会重启一下，重启后开启vnc需要在ssh终端输入vncserver"
reboot

done
